FROM registry.redhat.io/rhel9/nodejs-20-minimal as build

USER 1001

WORKDIR /opt/app-root/src/spaship

COPY --chown=1001:0 lerna.json ./
COPY --chown=1001:0 package.json ./
COPY --chown=1001:0 packages ./packages
COPY --chown=1001:0 package-lock.json ./


RUN cd packages/common && \
    npm install && \
    npm link && \
    cd ../router && \
    npm link @spaship/common && \
    rm -rf /opt/app-root/src/.npm


WORKDIR /opt/app-root/src/spaship/packages/router


FROM registry.redhat.io/rhel9/nodejs-20-minimal

USER 1001

WORKDIR /opt/app-root/src/spaship/packages

COPY --from=build /opt/app-root/src/spaship/packages/common ./common
COPY --from=build /opt/app-root/src/spaship/packages/router ./router

WORKDIR /opt/app-root/src/spaship/packages/router

EXPOSE 8765

CMD [ "npm", "start" ]