kind: ConfigMap
apiVersion: v1
metadata:
  name: config-{{ include "spa-deployment-operator.fullname" . }}
  labels:
  {{- include "spa-deployment-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  OPERATOR_EVENT_BUS_ADDRESS: {{ .Values.app.ec }}
  OPERATOR_DOMAIN_NAME: {{ .Values.app.domain }}
  APP_INSTANCE: {{ .Values.app.instance }}
  APPLICATION_WEBPROP_NS_DEFAULT: {{ .Values.app.defaultns }}
  MPP_TENANT_NAME: {{ .Values.app.tenant }}
  MPP_APP_CODE: {{ .Values.app.appcode }}
  MPP_PARENT_RB_NAME: role-{{ include "spa-deployment-operator.fullname" . }}
  MPP_DE_DEFAULT_NAMESPACE: {{ .Values.app.dedefaultns }}
  APPLICATION_DEVOPS_NAMING_CONVENTION: {{ include "spa-deployment-operator.fullname" . }}
