{{- if .Values.ingress.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-{{ include "spa-deployment-operator.fullname" . }}
spec:
  rules:
    - host: {{ .Values.nameOverride }}.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-{{ include "spa-deployment-operator.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- end }}