apiVersion: v1
kind: Service
metadata:
  name: svc-{{ include "spa-deployment-operator.fullname" . }}
  labels:
  {{- include "spa-deployment-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "spa-deployment-operator.selectorLabels" . | nindent 4 }}
