apiVersion: v1
kind: Template
labels:
  template: spaship-mongodb-template
metadata:
  name: spaship-mongodb-template
  annotations:
    "description": ""
    "iconClass": "icon-github"
    "openshift.io/display-name": "SPAship"
    "openshift.io/provider-display-name": "SPAship"
    "openshift.io/support-url": "https://github.com/spaship/spaship"
    "openshift.io/documentation-url": "https://spaship.io"
    "tags": "spaship,spa,mongodb"
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${name}-www
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: ${WWW_VOLUME_CAPACITY}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${MONGODB_SERVICE_NAME}
      labels:
        name: "${MONGODB_SERVICE_NAME}"
    stringData:
      database-user: "${MONGODB_USER}"
      database-password: "${MONGODB_PASSWORD}"
      database-admin-password: "${MONGODB_ADMIN_PASSWORD}"
      database-name: "${MONGODB_DATABASE}"
      database-replica-name: "${MONGODB_REPLICA_NAME}"
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${name}-httpd-config
    data:
      forbidden.conf: |-
        <FilesMatch "^spaship\.yaml">
            Require all denied
        </FilesMatch>
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${name}-httpd-ssi
    data:
      index.html: >-
        <!--#if expr="v('HTTP_COOKIE') =~ /rh_locale=(en|ja|ko|zh_CN)/ && $1 =~
        /(.*)/" -->
            <!--#set var="locale" value="$0" -->
        <!--#else -->
            <!--#set var="locale" value="en" -->
        <!--#endif -->
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${name}-api-config
    data:
      API_PORT: "8080"
      AUTH__KEYCLOAK__CLIENTID: ${KEYCLOAK_CLIENTID}
      AUTH__KEYCLOAK__REALM: ${KEYCLOAK_REALM}
      AUTH__KEYCLOAK__URL: ${KEYCLOAK_URL}
      AUTH__KEYCLOAK__ID_PROP: ${KEYCLOAK_ID_PROP}
      AUTH__KEYCLOAK__PUBKEY: ${KEYCLOAK_PUBKEY}
      LOG_FORMAT: json
      WEBROOT: /var/www/html
      UPLOAD_DIR: /tmp
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${name}-router-config
    data:
      LOG_FORMAT: json
      ROUTER_PORT: "8080"
      webroot: /var/www/html
      target: http://${name}-httpd:8080
      FALLBACK: ""
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${name}-httpd
        tag: ${tag}
      name: ${name}-httpd
    spec:
      replicas: ${replica}
      selector:
        app: ${name}-httpd
        deploymentconfig: ${name}-httpd
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${name}-httpd
            deploymentconfig: ${name}-httpd
            tag: ${tag}
        spec:
          volumes:
            - name: webroot
              persistentVolumeClaim:
                claimName: ${name}-www
            - name: ssi-init
              configMap:
                defaultMode: 420
                items:
                  - key: index.html
                    path: index.html
                name: ${name}-httpd-ssi
          containers:
            - image: spaship/httpd:${tag}
              name: ${name}-httpd
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: ${cpu_limit}
                requests:
                  cpu: ${cpu_request}
              volumeMounts:
                - name: webroot
                  mountPath: /var/www/html
                - name: ssi-init
                  mountPath: /var/www/html/.include/init
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: Always
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext:
            supplementalGroups:
              - 10000003
          terminationGracePeriodSeconds: 30
      test: false
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${name}-api
        tag: ${tag}
      name: ${name}-api
    spec:
      replicas: ${replica}
      selector:
        app: ${name}-api
        deploymentconfig: ${name}-api
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${name}-api
            deploymentconfig: ${name}-api
            tag: ${tag}
        spec:
          volumes:
            - name: webroot
              persistentVolumeClaim:
                claimName: ${name}-www
          containers:
            - image: spaship/api:${tag}
              name: ${name}-api
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: SPASHIP_DB__MONGO__USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: ${name}-mongodb
                - name: SPASHIP_DB__MONGO__PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: ${name}-mongodb
                - name: SPASHIP_DB__MONGO__DB_NAME
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: ${name}-mongodb
                - name: SPASHIP_DB__MONGO__URL
                  value: ${MONGODB_SERVICE_NAME}-0.${MONGODB_SERVICE_NAME}-internal:27017,${MONGODB_SERVICE_NAME}-1.${MONGODB_SERVICE_NAME}-internal:27017,${MONGODB_SERVICE_NAME}-2.${MONGODB_SERVICE_NAME}-internal:27017
              envFrom:
                - configMapRef:
                    name: ${name}-api-config
                  prefix: SPASHIP_
              resources:
                limits:
                  cpu: ${cpu_limit}
                requests:
                  cpu: ${cpu_request}
              volumeMounts:
                - name: webroot
                  mountPath: /var/www/html
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /liveness
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /readiness
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext:
            supplementalGroups:
              - 10000003
          terminationGracePeriodSeconds: 30
      test: false
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${name}-router
        tag: ${tag}
      name: ${name}-router
    spec:
      replicas: ${{replica}}
      selector:
        app: ${name}-router
        deploymentconfig: ${name}-router
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${name}-router
            deploymentconfig: ${name}-router
            tag: ${tag}
        spec:
          volumes:
            - name: webroot
              persistentVolumeClaim:
                claimName: ${name}-www
          containers:
            - image: spaship/router:${tag}
              name: ${name}-router
              ports:
                - containerPort: 8080
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: ${name}-router-config
                  prefix: SPASHIP_
              resources:
                limits:
                  cpu: ${cpu_limit}
                requests:
                  cpu: ${cpu_request}
              volumeMounts:
                - name: webroot
                  mountPath: /var/www/html
              terminationMessagePath: /dev/termination-log
              imagePullPolicy: Always
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext:
            supplementalGroups:
              - 10000003
          terminationGracePeriodSeconds: 30
      test: false
  # A non-headless service which takes pod readiness into consideration
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
      labels:
        name: "${MONGODB_SERVICE_NAME}"
    spec:
      # the list of ports that are exposed by this service
      ports:
        - name: mongodb
          port: 27017
      # will route traffic to pods having labels matching this selector
      selector:
        name: "${MONGODB_SERVICE_NAME}"

  # A headless service to create DNS records
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}-internal"
      labels:
        name: "${MONGODB_SERVICE_NAME}"
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    spec:
      clusterIP: None
      # the list of ports that are exposed by this service
      ports:
        - name: mongodb
          port: 27017
      # will route traffic to pods having labels matching this selector
      selector:
        name: "${MONGODB_SERVICE_NAME}"
  - kind: StatefulSet
    apiVersion: apps/v1beta1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
    spec:
      # pets get DNS/hostnames that follow the pattern: ${metadata.name}-NUM.${spec.serviceName}.default.svc.cluster.local
      serviceName: "${MONGODB_SERVICE_NAME}-internal"
      replicas: 3
      # describes the pod that will be created if insufficient replicas are detected
      template:
        metadata:
          # this label will be used for count running pods
          labels:
            name: "${MONGODB_SERVICE_NAME}"
        spec:
          containers:
            - name: mongo-container
              image: "${MONGODB_IMAGE}"
              ports:
                - containerPort: 27017
              args:
                - "run-mongod-pet"
              volumeMounts:
                - name: mongo-data
                  mountPath: "/var/lib/mongodb/data"
              env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: "${MONGODB_SERVICE_NAME}"
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: "${MONGODB_SERVICE_NAME}"
                - name: MONGODB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: "${MONGODB_SERVICE_NAME}"
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-admin-password
                      name: "${MONGODB_SERVICE_NAME}"
                - name: MONGODB_REPLICA_NAME
                  valueFrom:
                    secretKeyRef:
                      key: database-replica-name
                      name: "${MONGODB_SERVICE_NAME}"
                - name: MONGODB_KEYFILE_VALUE
                  value: "${MONGODB_KEYFILE_VALUE}"
                - name: MONGODB_SERVICE_NAME
                  value: "${MONGODB_SERVICE_NAME}-internal"
              resources:
                limits:
                  memory: "512Mi"
              readinessProbe:
                exec:
                  command:
                    - stat
                    - /tmp/initialized
      volumeClaimTemplates:
        - metadata:
            name: mongo-data
            labels:
              name: "${MONGODB_SERVICE_NAME}"
            annotations:
              # Uncomment this if using dynamic volume provisioning.
              # https://docs.openshift.org/latest/install_config/persistent_storage/dynamically_provisioning_pvs.html
              # volume.alpha.kubernetes.io/storage-class: anything
          spec:
            # the volume can be mounted as read-write by a single node
            accessModes: [ ReadWriteOnce ]
            resources:
              requests:
                storage: "${DATABASE_VOLUME_CAPACITY}"
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${name}-httpd
      name: ${name}-httpd
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${name}-httpd
        deploymentconfig: ${name}-httpd
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${name}-api
      name: ${name}-api
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${name}-api
        deploymentconfig: ${name}-api
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${name}-router
      name: ${name}-router
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${name}-router
        deploymentconfig: ${name}-router
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        haproxy.router.openshift.io/disable_cookies: "true"
        haproxy.router.openshift.io/timeout: "10m"
      labels:
        app: ${name}-api
      name: ${name}-api
    spec:
      host: ${name}-api${urlSuffix}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${name}-api
        weight: 100
      wildcardPolicy: None
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        haproxy.router.openshift.io/disable_cookies: "true"
      labels:
        app: ${name}-router
      name: ${name}-router
    spec:
      host: ${name}-router${urlSuffix}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${name}-router
        weight: 100
      wildcardPolicy: None
parameters:
  - name: name
    displayName: Name Prefix
    description: Component name prefix
    value: spaship
    required: true
  - name: tag
    displayName: Version
    description: SPAship tag
    required: true
    value: latest
  - name: urlSuffix
    displayName: Url Suffix
    description: Router url suffix for spaship-router and spaship-api
    required: true
  - name: replica
    description: number of replicas
    value: "1"
    required: false
  - name: cpu_limit
    displayName: CPU limit
    description: CPU limit
    value: "100m"
  - name: cpu_request
    displayName: CPU request
    description: CPU request
    value: "25m"
  - name: WWW_VOLUME_CAPACITY
    displayName: "WWW Volume Capacity"
    description: "Volume space available for www data, e.g. 512Mi, 2Gi."
    value: "2Gi"
    required: true
  - name: DATABASE_VOLUME_CAPACITY
    displayName: "Database Volume Capacity"
    description: "Volume space available for database data, e.g. 512Mi, 2Gi."
    value: "2Gi"
    required: true
  - name: MONGODB_USER
    displayName: MongoDB Connection Username
    description: Username for MongoDB user that will be used for accessing the database.
    required: true
    generate: expression
    from: "user[A-Z0-9]{3}"
  - name: MONGODB_PASSWORD
    displayName: MongoDB Connection Password
    description: Password for the MongoDB connection user.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: MONGODB_DATABASE
    displayName: MongoDB Database Name
    description: Name of the MongoDB database accessed.
    required: true
    value: spaship
  - name: MONGODB_ADMIN_PASSWORD
    displayName: MongoDB Database Name
    description: Password for the database admin user.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: MONGODB_REPLICA_NAME
    displayName: "Replica Set Name"
    description: "The name of the replica set."
    value: rs0
    required: true
  - name: MONGODB_KEYFILE_VALUE
    displayName: "Keyfile Content"
    description: "The value of the MongoDB keyfile (https://docs.mongodb.com/manual/core/security-internal-authentication/#internal-auth-keyfile)."
    generate: expression
    from: "[a-zA-Z0-9]{255}"
    required: true
  - name: MONGODB_IMAGE
    displayName: "MongoDB Docker Image"
    description: "A reference to a supported MongoDB Docker image."
    value: "registry.access.redhat.com/rhscl/mongodb-36-rhel7"
    required: true
  - name: MONGODB_SERVICE_NAME
    displayName: "OpenShift Service Name"
    description: "The name of the OpenShift Service exposed for the database."
    value: spaship-mongodb
    required: true
  - name: KEYCLOAK_CLIENTID
    displayName: "Keycloak Client ID"
    description: "The Keycloak client id for your SPAship Manager instance."
    required: true
  - name: KEYCLOAK_REALM
    displayName: "Keycloak REALM"
    description: "The Keycloak Realm under which your SPAship Manager client is registered."
    required: true
  - name: KEYCLOAK_URL
    displayName: "Keycloak URL"
    description: "The URL to a Keycloak instance you wish to use for authentication."
    required: true
  - name: KEYCLOAK_ID_PROP
    displayName: "JWT user UUID prop"
    description: "The JWT property to treat as a UUID."
    required: true
  - name: KEYCLOAK_PUBKEY
    displayName: "Keycloak public key"
    description: "Your Keycloak realm's public key."
    required: true
