kind: "Template"
apiVersion: "v1"
metadata:
  name: "namespace-template"
labels:
  template: "namnespace-template"
parameters:
  - name: "APP_CODE"
    description: "App code of the parent project"
    required: true
  - name: "TENANT_NAME"
    description: "Name of the parent project"
    required: true
  - name: "WEB_PROPERTY_NAME"
    description: "based on web property name the automation will create the tenant"
    required: true
objects:
  - kind: TenantNamespace
    apiVersion: tenant.paas.redhat.com/v1alpha1
    metadata:
      name: ${WEB_PROPERTY_NAME}
      labels:
        paas.redhat.com/appcode: ${APP_CODE}
        tenant.paas.redhat.com/namespace-type: runtime
        tenant.paas.redhat.com/tenant: ${TENANT_NAME}
    spec:
      type: runtime
      network:
        security-zone: external

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-pod-and-namespace-both
      #namespace: spaship--qa
    spec:
      podSelector:
        matchLabels:
          managedBy: spaship
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  tenant.paas.redhat.com/tenant: ${TENANT_NAME}
            - podSelector:
                matchLabels:
                  managedBy: spaship
          ports:
            - protocol: TCP
              port: 8081
            - protocol: TCP
              port: 80
