---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spaship-api
  title: SPAship API
  namespace: devex
  description: Backend for the SPAship with the APIs.
  annotations:
    github.com/project-slug: 'spaship/spaship'
    servicenow.com/appcode: SPAS-002
  tags:
    - spaship
    - developers
    - nodejs
    - xe
spec:
  type: service
  lifecycle: production
  owner: group:redhat/spaship-devs
  system: devex/spaship